# Generated by Django 5.0.7 on 2024-07-17 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarblog',
            name='concept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.grammarconcept'),
            preserve_default=False,
        ),
    ]
