# Generated by Django 5.0.7 on 2024-07-18 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_grammarblog_concept'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammartest',
            name='answer',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grammartest',
            name='concept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.grammarconcept'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grammartest',
            name='question',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='grammartest',
            table='GrammarTests',
        ),
    ]
