# Generated by Django 5.0.7 on 2024-07-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_grammartest_instruction_grammartest_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammartest',
            name='option_one',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grammartest',
            name='option_three',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grammartest',
            name='option_two',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grammartest',
            name='instruction',
            field=models.TextField(null=True),
        ),
    ]
