# Generated by Django 5.0.7 on 2024-07-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_grammartest_option_one_grammartest_option_three_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammartest',
            name='instruction',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grammartest',
            name='option_one',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grammartest',
            name='option_three',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grammartest',
            name='option_two',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
    ]
