# Generated by Django 5.0.7 on 2024-07-18 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_grammartestsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammartest',
            name='test_section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.grammartestsection'),
            preserve_default=False,
        ),
    ]
