# Generated by Django 5.0.7 on 2024-07-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_grammartest_test_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammartest',
            name='feedback',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
