# Generated by Django 5.0.7 on 2024-07-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_grammartest_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammartest',
            name='feedback',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
