# Generated by Django 5.0.7 on 2024-07-18 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_grammartest_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammartest',
            name='concept',
        ),
        migrations.RemoveField(
            model_name='grammarblog',
            name='concept',
        ),
        migrations.AddField(
            model_name='grammartestsection',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.grammarblog'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GrammarConcept',
        ),
    ]
