# Generated by Django 5.0.7 on 2024-07-21 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_grammartest_concept_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=45)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grammarblog')),
            ],
            options={
                'db_table': 'grammarassessment',
            },
        ),
    ]
