# Generated by Django 5.0.7 on 2024-07-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_grammarassessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammartest',
            name='instruction',
        ),
        migrations.AddField(
            model_name='grammartestsection',
            name='instruction',
            field=models.TextField(blank=True),
        ),
    ]
