# Generated by Django 5.0.4 on 2024-05-06 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjunctive', '0002_remove_sentence_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
